apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-greetings-dev
  labels:
    app: python-greetings-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-greetings-dev
  template:
    metadata:
      labels:
        app: python-greetings-dev
    spec:
      containers:
      - name: python-greetings-dev-pod
        image: teodorajovcheska7/python-greetings-app
        ports:
        - containerPort: 3000
