apiVersion: v1
kind: Service
metadata:
  name: python-greetings-service-dev
spec:
  selector:
    app: python-greetings-dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer