apiVersion: v1
kind: Service
metadata:
  name: python-greetings-service
spec:
  selector:
    app: python-greetings
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer